### ISSUE TITLE
Make metric export interval configurable

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-node#138]
JS doesn't support this environment variable `OTEL_METRIC_EXPORT_INTERVAL` (yet?). Looks like [environment variable support is optional](https://github.com/open-telemetry/opentelemetry-specification/blob/main/spec-compliance-matrix.md#environment-variables).

I think we'll have to add this as a config option in our distro if we want to use it, maybe as an env var, until it's added upstream. It is an option on the `PeriodicExportingMetricReader` for [`exportIntervalMillis`](https://github.com/open-telemetry/opentelemetry-js/blob/2fb80ebe19c7fb16704fb39e3df1faa4845a9f8c/packages/sdk-metrics/src/export/PeriodicExportingMetricReader.ts#L87), and the default seems to be 60s.

_Originally posted by @JamieDanielson in https://github.com/honeycombio/honeycomb-opentelemetry-node/pull/132#discussion_r1048897065_

**Comment by pkanal** [comment]
@JamieDanielson what do you think about us just adding `OTEL_METRIC_EXPORT_INTERVAL` env var support to the distro and not making it a honeycomb specific configuration option? That way it stays consistent with the other distros and when support is added upstream it should just work.
