### ISSUE TITLE
Consider making it easier to specify a different processor?

### ISSUE THREAD

**Issue by cartermp** [honeycombio/honeycomb-opentelemetry-node#162]
IDK if this is 100% coherent, buuuuutt it'd be nice to just say "give me `SimpleSpanProcessor`" without any additional configuration. This can be helpful for short-lived tasks or scripts that don't need the benefits of a `BatchSpanProcessor`.

**Comment by MikeGoldsmith** [comment]
The SimpleSpanProcessor requires an exporter, so is always expected to export telemetry. Do you mean you'd like to see a generic simple processor that can perform a custom task but not expected to export telemtry?

**Comment by cartermp** [comment]
Yeah, it might be nice to be able to say "actually use this processor instead" without having to specify an exporter. Although that does cross into weirder territory I suppose, since it's more sugar over the standard SDK APIs for configuring this stuff.

**Comment by MikeGoldsmith** [comment]
I think that would be an implementation of the SpanProcessor interface?

**Comment by MikeGoldsmith** [comment]
For example, you could create a class that implements the SDKs [SpanProcesspr](https://github.com/open-telemetry/opentelemetry-js/blob/47444f2a4c13a80f3328ffafc5b4c8db9e9a0886/packages/opentelemetry-sdk-trace-base/src/SpanProcessor.ts#L25) interface and add it to your tracer provider.

I'm gonna close this, feel free to re-open if you feel it needs more attension.
