### ISSUE TITLE
Some 'valid' options have no effect. 

### ISSUE THREAD

**Issue by Jwhiles** [honeycombio/honeycomb-opentelemetry-node#176]
Hello!

I've been using this package to record telemetry to honeycomb, and ran into a bit of an issue. The options type for the honeycomb SDK gets defined [here](https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/src/honeycomb-options.ts#L27) and is essentially an extension of the existing `NodeSDKConfiguration` interface. That interface includes a property `sampler` which accepts a custom sampler. Going from the types exposed by honeycomb-opentelemetry-node this appears like it should also be accepted by this package, however if we pass a custom sampler it's never used because that property is overwritten [here](https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/main/src/opentelemetry-node.ts#L24).

This led me to spend a few minutes confused about why my custom sampler didn't work. I've made [a fork](https://github.com/Jwhiles/honeycomb-opentelemetry-node/commit/52a3998bbebd8c060e8324a3908ebbf8b8d10011#diff-c3eaaf5f38f8e1affa13a88f2b69467d532b2a9b3b16422bd8891287232f03e1R24) to fix this for my use case. Ideally I'd like to see this functionality in this repo - or alternatively for the types to be updated to make `sampler` an invalid option.

:)

**Comment by robbkidd** [comment]
Thanks for catching this issue, @Jwhiles. Hmm. Our goal with the OTel distributions is to provide an Easy Button for getting started with OpenTelemetry. At a point where an application developer has their own custom sampler—often a Dark Art of its own—they might have a better experience using the upstream OpenTelemetry SDK and select which components of the Honeycomb library to mix in.

For the foreseeable future, we'll probably opt for your second suggestion: update the function and type to not accept a sampler.

**Comment by robbkidd** [comment]
@Jwhiles As an alternative to maintaining a fork, you could use the upstream OpenTelemetry NodeSDK instance and configure the Honeycomb-specific things within it directly.

For example:

```js
const honeycombHeaders = new Metadata();
honeycombHeaders.set("x-honeycomb-team", process.env.HONEYCOMB_API_KEY);

const honeycombExporter = new OTLPTraceExporter({
  url: process.env.HONEYCOMB_API_ENDPOINT,
  metadata: honeycombHeaders,
});

const sdk: NodeSDK = new NodeSDK({
  serviceName: yourServiceName,
  sampler: yourSampler,
  traceExporter: honeycombExporter,
  instrumentations: [
    // …
  ],
});
```

Keep in mind that if your sampler sends spans at a ratio other than 1:1, something ought to add to the sampled spans—the spans that _are_ sent—an attribute named `sample_rate` with an integer value set for how many not-sampled (i.e. _not_ sent) spans the one that was sent represents.

**Comment by pkanal** [comment]
@Jwhiles after some discussion we've decided to support overwriting any of the `NodeSDK` properties with user provided properties, this should allow you to supply your own custom sampler. The support for this is out in [v0.5.0](https://github.com/honeycombio/honeycomb-opentelemetry-node/releases/tag/v0.5.0).
