### ISSUE TITLE
Have a way to skip `console.warn` logs on initialisation

### ISSUE THREAD

**Issue by JGAntunes** [honeycombio/honeycomb-opentelemetry-node#201]
**Is your feature request related to a problem? Please describe.**

As part of integrating Honeycomb and open telemetry in - https://github.com/netlify/build - we've spotted there's a set of console warnings that always show up when initialising the SDK:

- https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/ed5b096b16bc88cc12b08d0c5e4a50c6df894140/src/honeycomb-options.ts#L108-L126

We're using an open telemetry collector which exports traces to Honeycomb directly, however we would still like to leverage the packaged `spanProcessor`, `traceExporter`, etc. that the `@honeycombio/opentelemetry-node` module exports.

- https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/ed5b096b16bc88cc12b08d0c5e4a50c6df894140/src/opentelemetry-node.ts#L15-L32

These warnings however won't let us use the SDK directly in prod since our process execution is customer facing and so are the logs it produces (including the warnings mentioned above ☝️) and for which we have no control over. 

**Describe the solution you'd like**

Having a way to optionally disable the logs? Either by only logging when `opts.debug === true` or by having a specific flag we could check? (e.g. `opts.skipOptionsValidation` or something like that)

**Describe alternatives you've considered**

I guess we can manually setup our own `NodeSDK` and potentially use the components this module exports directly, something like (still struggling with some type incompatibilies which I think are related with the versions imported):

- https://github.com/netlify/build/pull/5118/files#diff-35d5071f64c34495a145ae226bb81b0acd6f2ab47df520291055562c4716aab7L32

Nevertheless I think it's extra setup work we could bypass if we had a way to bypass the warning logs 👍 

**Additional context**

**Comment by MikeGoldsmith** [comment]
Hey @JGAntunes - thanks for creating the issue. I understand the desire for not showing warnings when using the SDK with a collector. We'll look into adding a way to ignore those warnings as you've suggested 👍🏻
