### ISSUE TITLE
Setup a parent based sampler

### ISSUE THREAD

**Issue by JGAntunes** [honeycombio/honeycomb-opentelemetry-node#203]
**Is your feature request related to a problem? Please describe.**

Related with a recent integration in a project of ours - https://github.com/netlify/build/pull/5118 - we're passing over a set of remote `traceId`, `spanId` and `traceFlags` to create a parent span we can use to stitch together a full trace of our system:
- https://github.com/netlify/build/blob/705b93a8c59af878b5c698d1a3d9a04e7528b27e/packages/build/src/tracing/main.ts#L44-L51

The problem we're facing is that it seems like the current sampler in place is not aware of the parent span context:
- https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/a2da97851f6d443a8ac4fafe3844c38cb8912b7c/src/deterministic-sampler.ts#L38-L66

And we have no way of overriding it since the `opts` spread in the `HoneycombSDK` constructor is being overriden by the `DeterministicSampler` creation:
- https://github.com/honeycombio/honeycomb-opentelemetry-node/blob/a2da97851f6d443a8ac4fafe3844c38cb8912b7c/src/opentelemetry-node.ts#L18-L25

**Describe the solution you'd like**

Either wrap the current default `DeterministicSampler` with a `ParentBasedSampler` so that the parent span context is used out of the box or alternatively allow us to override the default `sampler`.

**Describe alternatives you've considered**

None that I could think of but definitely open to it 👍 

**Additional context**

**Comment by JGAntunes** [comment]
Created a couple of PRs (#204 and #205) which address both problems. Let me know what you all think 👍

**Comment by MikeGoldsmith** [comment]
As mentioned in a comment in #205 [comment](https://github.com/honeycombio/honeycomb-opentelemetry-node/pull/205#issuecomment-1625509125).

I've approved #204 as this allows user better access to override some more distro PRs.

**Comment by JGAntunes** [comment]
Thank you @MikeGoldsmith 🙏

Something I realised though when you reviewed the PRs and I went on to read the spec for the `TraceIdRatioBasedSampler` is that, given a `traceID` and a `sampleRate`, the resulting sample decision will always be the same is that correct (hence the `DeterministicSampler` behaviour 🤦)? So in fact our problem would be solved if, besides passing on a `traceID` we also use the same `sampleRate`, we should get consistent sampling across the whole trace.

Nevertheless I think #204 is still useful so happy to follow up on that 👍

**Comment by MikeGoldsmith** [comment]
Yes, that's correct - the TraceID ratio samplers are meant to be deterministic based on Trace ID and will consistently return the same result for the same Trace ID. Our sampler effectively just wraps this behaviour and returns the selected sample rate in the sampling decision result which are added to the span before it's exported. We have custom handling of the "SampleRate" attribute in our backend to calculate real population size. The default samplers do not return the ratio as an attribute.
