### ISSUE TITLE
trace.getTracer broken with Honeycomb

### ISSUE THREAD

**Issue by dcposch** [honeycombio/honeycomb-opentelemetry-node#239]
### Versions
```
    "@honeycombio/opentelemetry-node": "^0.5.0",
    "@opentelemetry/api": "^1.6.0",
    "@opentelemetry/auto-instrumentations-node": "^0.39.3",
```

### Steps to reproduce

1. Set up HoneycombSDK as recommended in the quick start
    
    tracing.ts
    ```ts
    import { HoneycombSDK } from "@honeycombio/opentelemetry-node";
    import { getNodeAutoInstrumentations } from "@opentelemetry/auto-instrumentations-node";
    
    console.log(`[TRACING] initializing Honeycomb...`);
    const sdk = new HoneycombSDK({
      instrumentations: [
        getNodeAutoInstrumentations({
          "@opentelemetry/instrumentation-fs": { enabled: false },
        }),
      ],
    });
    sdk.start();
    ```

2. Try to record a trace
    
    main.ts
    ```ts
    const tracer = trace.getTracer("test-dataset");
    tracer.startActiveSpan(`test`, async (span) => {
          span.setAttribute("name", "bob");
          span.end();
    });
    ```

### Expected result

Auto-instrumented traces, plus the test test trace show up in Honeycomb.

### Actual result

Auto-instrumented traces only.

**The test trace is silently dropped with no error message.**

### Additional context

I used Honeycomb extensively a few years ago and appreciated its simplicity.

It's really sad to see it become this large, complicated, InjectedFactoryInstanceGenerator-esque thing.

**Comment by JamieDanielson** [comment]
@dcposch can you confirm whether you've imported trace from the opentelemetry api package? 

```js
import { trace } from '@opentelemetry/api';
```

A next step to try is to enable [Debug mode](https://docs.honeycomb.io/getting-data-in/opentelemetry/node-distro/#debug-mode) with `export DEBUG=true` or as a property in the SDK initialization `debug: true`. That will show configuration, what's registered and patched, and also will log the spans to the console. For example, part of the output in the [hello-node example](https://github.com/honeycombio/honeycomb-opentelemetry-node/tree/main/examples/hello-node) when debug is set to true looks like this:

```log
@opentelemetry/instrumentation-http Applying patch for http@19.8.1
@opentelemetry/api: Registered a global for trace v1.4.1.
@opentelemetry/api: Registered a global for context v1.4.1.
@opentelemetry/api: Registered a global for propagation v1.4.1.

...

@opentelemetry/instrumentation-http http instrumentation incomingRequest
saying hello to the world
items to be sent [
  Span {
    attributes: { SampleRate: 1, message: 'hello-world' },

...

    instrumentationLibrary: {
      name: 'hello-world-tracer',
```

**Comment by dcposch** [comment]
> can you confirm whether you've imported trace from the opentelemetry api package?

Yes, the import looks exactly like above.

I tried debug mode and get a deluge of logs on startup, but after that:

- I see the (correctly logged) autoinstrumented spans in the debug logs, but
- **I don't see any output for manual spans.**

When I `console.log(span.isRecording)`, it prints false. This makes me think that `tracer.startSpan` is silently returning a span destined to be ignored.

**Comment by MikeGoldsmith** [comment]
Hi @dcposch - we've had some reports the distro doesn't play nicely with some of the newer OTel packages. I've prepared an update for our distro to use the [latest OTel packages](https://github.com/honeycombio/honeycomb-opentelemetry-node/pull/241) and will do a release once merged.

I'll ping here again once it's ready for you to try.

**Comment by MikeGoldsmith** [comment]
Hi @dcposch -[v0.6.0](https://github.com/honeycombio/honeycomb-opentelemetry-node/releases/tag/v0.6.0) of the Honeycomb distro has been released. Please can you give it a try?

**Comment by dcposch** [comment]
Works now, thanks you.

I was definitely pulling my hair out yesterday... based on the diff it looks like the issue involved a wrong version of otel packages, maybe `opentelemetry/api` ?

Might be worth making that a peerDependency; then users of this package won't end up with 2 conflicting versions of the otel ones.
