### ISSUE TITLE
Upgrade OpenTelemetry dependencies.

### ISSUE THREAD

**Issue by gtrrz-victor** [honeycombio/honeycomb-opentelemetry-node#292]
I am facing a peer dependency conflict in my monorepo project, which includes both a frontend and a backend app. Both apps use OpenTelemetry.

The frontend project uses `@opentelemetry/auto-instrumentations-web`: 0.36.0, which depends on:
- `@opentelemetry/instrumentation`: 0.48.0. 

On the other hand, the backend uses `@honeycombio/opentelemetry-node`: 0.7.0, which depends on:
- `@opentelemetry/sdk-node`: 0.46.0. This, in turn, depends on:
  -  `@opentelemetry/instrumentation`: 0.46.0.

I could use an older version of `@opentelemetry/auto-instrumentations-web` to match the `@opentelemetry/instrumentation` version, but `@opentelemetry/instrumentation` has [this bug](https://github.com/open-telemetry/opentelemetry-js/pull/4386) which needs to be fixed to be able to add web OpenTelemetry, it was fixed in version 0.47.0 

Ideally, Honeycomb would upgrade all of its OpenTelemetry dependencies. I noticed there's already an open PR for this (https://github.com/honeycombio/honeycomb-opentelemetry-node/pull/286) , but it's failing on the smoke test step. It would be great if we could incorporate that PR into Honeycomb.

Thank you very much.

**Comment by JamieDanielson** [comment]
Thanks for reporting! [Release v0.7.1](https://github.com/honeycombio/honeycomb-opentelemetry-node/releases/tag/v0.7.1) is now available that should help resolve this problem!
