### ISSUE TITLE
Incompatibility with @opentelemetry/api 1.8.0

### ISSUE THREAD

**Issue by zaq42** [honeycombio/honeycomb-opentelemetry-node#293]
We’ve lost a week of tracing because these don’t play nice:
```
"@honeycombio/opentelemetry-node": "^0.7.0" 
"@opentelemetry/api": "^1.8.0",
```

This error is logged:

```
Error: @opentelemetry/api: Registration of version v1.8.0 for trace does not match previously registered API v1.7.0
```
I’ve traced it back to [this commit](https://github.com/honeycombio/honeycomb-opentelemetry-node/commit/67548d949e78188871398d00f177301466eed626)… 

The stated intention of [PR#268](https://github.com/honeycombio/honeycomb-opentelemetry-node/pull/268) was to avoid:
> Experimental packages can have bigger (even breaking) changes in a minor version, which makes a caret (minor) unpredictable. A tilde can be used for allowing patches only.

However, I think the `@opentelemetry/api` can be trusted for proper versioning.

In the meantime, I need to either pin @opentelemetry/api to 1.7.0 until [PR#286](https://github.com/honeycombio/honeycomb-opentelemetry-node/pull/286) is resolved, or remove my explicit dependency.

**Comment by JamieDanielson** [comment]
Thanks for reporting! [Release v0.7.1](https://github.com/honeycombio/honeycomb-opentelemetry-node/releases/tag/v0.7.1) is now available that should help resolve this problem!

**Comment by zaq42** [comment]
Thanks for the rapid response.  0.7.1 works for us and resolves this issue.

I'm still a little concerned about the use of the `~` for the api version... it's essentially saying "we don't trust `@opentelemetry/api` to properly use semantic versioning."

As it stands, this specific problem is quite likely to occur on the next version bump.

**Comment by joshkel** [comment]
I'd like to also request reconsidering the use of `~` for versions - or, alternatively, make loud and obvious error messages in case of version mismatch.

In our case, we're trying to get up and running with Honeycomb and OpenTelemetry, but none of our parent span relationships were working. The problem was the result of `@honeycombio/opentelemetry-node` pinning to different versions of `@opentelemetry` packages - that resulted in two different installations of `@opentelemetry` packages and two different instances of the global OTel context manager, which broke span resolution.

**Comment by joshkel** [comment]
More information, in case it helps: Changing `@honeycombio/opentelemetry-node`'s dependencies for `@opentelemetry/api` only from `~` to `^` appears sufficient to fix the incompatibility we noticed. So, at least for that issue, dependencies on other OTel packages can continue to use `~` as in #268. (All my tests were done with the Yarn 4.x package manager.)

Another possible solution, as I understand it, would be to specify `"@opentelemetry/api": "~1.7.0"` (etc.) under  `@honeycombio/opentelemetry-node`'s `peerDependencies` - then users' package managers can warn them about potential incompatibilities.

**Comment by JamieDanielson** [comment]
Thanks for the input @joshkel and @zaq42 ! I opened PR #299 to at least ease the restriction on the API version. I'm not positive on the definite best route to take, as the overall intention is indeed to minimize incompatibilities. The `peerDependencies` might be something to consider as well, though I believe that will require installs if those packages are not installed by the end user (which they may not need to be). Perhaps [`peerDependenciesMeta`](https://docs.npmjs.com/cli/v7/configuring-npm/package-json#peerdependenciesmeta) is the solution 🤔  as it allows peer dependencies to be marked optional.
