### ISSUE TITLE
[OKR] make 5 top pain points visible

### ISSUE THREAD

**Issue by vreynolds** [honeycombio/honeycomb-opentelemetry-node#85]
Make it easier to score the OKR by cleaning up the [paint points doc](https://honeycomb.quip.com/hP84Annv7ZMh#KZQABAaRWA3) so the 5 points are easy to see

**Comment by JamieDanielson** [comment]
https://honeycomb.quip.com/hP84Annv7ZMh/otel-js-pain-points#temp:C:KZQ23e7975301ec4d96ac4c67941
