### ISSUE TITLE
docs: add sdk to one service in 🍳 example greeting service 🍳

### ISSUE THREAD

**Issue by JamieDanielson** [honeycombio/honeycomb-opentelemetry-node#94]
**Is your feature request related to a problem? Please describe.**

To help ensure interoperability between beelines and vanilla OTel and this SDK, update one of the services in [Example Greeting Service](https://github.com/honeycombio/example-greeting-service/tree/main/node) to use the new honeycomb SDK.

**Comment by emilyashley** [comment]
https://github.com/honeycombio/honeycomb-opentelemetry-node/pull/107

**Comment by emilyashley** [comment]
closed by https://github.com/honeycombio/example-greeting-service/pull/264
